Set-StrictMode -Version Latest

enum NanoMarkupErrorCode { Syntax; Indentation; String; Escape; Key; DuplicateKey; Utf8; Value }
class NanoMarkupException : System.Exception { [NanoMarkupErrorCode]$Code; [int]$Line; [int]$Column; [int]$ByteOffset; NanoMarkupException([NanoMarkupErrorCode]$c,[string]$m,[int]$l=1,[int]$col=1,[int]$o=0):base($m){$this.Code=$c;$this.Line=$l;$this.Column=$col;$this.ByteOffset=$o} }

function ConvertFrom-NanoMarkup {
 [CmdletBinding()] param([Parameter(Mandatory,ValueFromPipeline)][object]$InputObject)
 process { $text = if ($InputObject -is [byte[]]) { try { [Text.Encoding]::UTF8.GetString($InputObject) } catch { throw [NanoMarkupException]::new([NanoMarkupErrorCode]::Utf8,'Invalid UTF-8') } } else { [string]$InputObject }; $lines=@($text -replace "`r`n", "`n" -split "`n"); $state=[pscustomobject]@{ Lines=$lines; Index=0 }; Read-NanoRoot $state }
}
function Read-NanoRoot($s) { while($s.Index -lt $s.Lines.Count -and (Test-NanoIgnored $s.Lines[$s.Index])){$s.Index++}; if($s.Index -ge $s.Lines.Count){return [ordered]@{}}; $p=Get-NanoParts $s $s.Lines[$s.Index];$s.Index++; if($p.Level -ne 0){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::Indentation,'Document root must begin at level zero',$s.Index)}; switch($p.Text){'..'{return Read-NanoMap $s 1};':'{return Read-NanoSeq $s 1};'|'{return Read-NanoMulti $s 1};default{return Read-NanoScalar $p.Text}} }
function Read-NanoMap($s,[int]$level){$map=[ordered]@{};while($s.Index -lt $s.Lines.Count){if(Test-NanoIgnored $s.Lines[$s.Index]){$s.Index++;continue};$p=Get-NanoParts $s $s.Lines[$s.Index];if($p.Level -lt $level){break};if($p.Level -gt $level){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::Indentation,'Unexpected indentation',$s.Index+1)};$s.Index++;$key=$null;$v=$null;if($p.Text.EndsWith('..')){$key=$p.Text.Substring(0,$p.Text.Length-2);$v=Read-NanoMap $s ($level+1)}elseif($p.Text.EndsWith(':')){$key=$p.Text.TrimEnd(':');$v=Read-NanoSeq $s ($level+1)}elseif($p.Text.EndsWith('|')){$key=$p.Text.TrimEnd('|');$v=Read-NanoMulti $s ($level+1)}else{$parts=$p.Text.Split(' ',2);$key=$parts[0];$v=Read-NanoScalar $(if($parts.Count -gt 1){$parts[1]}else{''})};if(-not(Test-NanoKey $key)){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::Key,'Invalid mapping key',$s.Index)};if($map.Contains($key)){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::DuplicateKey,'Duplicate mapping key',$s.Index)};$map[$key]=$v};return $map}
function Read-NanoSeq($s,[int]$level){$a=[Collections.Generic.List[object]]::new();while($s.Index -lt $s.Lines.Count){if(Test-NanoIgnored $s.Lines[$s.Index]){$s.Index++;continue};$p=Get-NanoParts $s $s.Lines[$s.Index];if($p.Level -lt $level){break};if($p.Level -gt $level){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::Indentation,'Unexpected indentation',$s.Index+1)};$s.Index++;$a.Add($(switch($p.Text){'..'{Read-NanoMap $s ($level+1)};':'{Read-NanoSeq $s ($level+1)};'|'{Read-NanoMulti $s ($level+1)};default{Read-NanoScalar $p.Text}}))};return @($a)}
function Read-NanoMulti($s,[int]$level){$prefix=' ' * ($level*4);$a=@();while($s.Index -lt $s.Lines.Count -and $s.Lines[$s.Index].StartsWith($prefix)){$a+=$s.Lines[$s.Index].Substring($prefix.Length);$s.Index++};return ($a -join "`n")}
function Read-NanoScalar([string]$x){if($x.StartsWith('"')){if(!$x.EndsWith('"') -or $x.Length -lt 2){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::String,'Missing closing quote')};$x=$x.Substring(1,$x.Length-2);return [regex]::Replace($x,'\\([nrt"\\])',{param($m) switch($m.Groups[1].Value){'n'{"`n"};'r'{"`r"};'t'{"`t"};default{$m.Groups[1].Value}}})};if([string]::IsNullOrEmpty($x) -or $x.StartsWith(' ') -or $x.EndsWith(' ')){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::String,'Invalid unquoted string')};return $x}
function ConvertTo-NanoMarkup { [CmdletBinding()]param([Parameter(Mandatory,ValueFromPipeline)]$InputObject,[ValidateSet("`n","`r`n")][string]$Newline="`n");process{$lines=[Collections.Generic.List[string]]::new();Write-NanoValue $InputObject 0 'root' $null $lines; $lines -join $Newline} }
function Write-NanoValue($v,[int]$level,[string]$ctx,[string]$key,$lines){$p=' ' * ($level*4);if($v -is [Collections.IDictionary]){$lines.Add($(if($ctx -eq 'root'){'..'}else{"$p$key.."}));foreach($k in $v.Keys){if(!(Test-NanoKey $k)){throw 'Invalid mapping key'};Write-NanoValue $v[$k] ($level+1) 'map' $k $lines}}elseif($v -is [Collections.IEnumerable] -and $v -isnot [string]){$lines.Add($(if($ctx -eq 'root'){':'}else{"${p}${key}:"}));foreach($x in $v){Write-NanoValue $x ($level+1) 'seq' $null $lines}}else{$x=[string]$v;if($x -match '[\x00-\x08\x0B\x0C\x0E-\x1F]'){throw 'Forbidden character'};$raw=$x.Length -gt 0 -and !$x.StartsWith(' ') -and !$x.EndsWith(' ') -and !$x.StartsWith('"') -and $x -notmatch '[\r\n\t]';$out=if($raw){$x}else{'"'+($x -replace '\','\\' -replace '"','\"' -replace "`n",'\n' -replace "`r",'\r' -replace "`t",'\t')+'"'};$lines.Add($(if($ctx -eq 'map'){if($x.Length -eq 0){"$p$key"}else{"$p$key $out"}}else{"$p$out"}))}}
function Get-NanoParts($s,[string]$line){$n=($line -replace '^([^ ]*).*','$1').Length;if($n%4){throw [NanoMarkupException]::new([NanoMarkupErrorCode]::Indentation,'Indentation must use four spaces',$s.Index+1)};[pscustomobject]@{Level=$n/4;Text=$line.Substring($n)}};function Test-NanoIgnored($x){$t=$x.TrimStart(' ');$t.Length -eq 0 -or $t.StartsWith('#')};function Test-NanoKey($x){$x -match '^[A-Za-z_][A-Za-z0-9_-]*$'}
Export-ModuleMember -Function ConvertFrom-NanoMarkup,ConvertTo-NanoMarkup
